### ISSUE TITLE
Locale callback throwing an error when sending email through cloud code

### ISSUE THREAD

**Issue by wlky** [mtrezza/parse-server-api-mail-adapter#20]
### New Issue Checklist
- [x ] I am not disclosing a [vulnerability](https://github.com/mtrezza/parse-server-api-mail-adapter/security/policy).
- [x ] I am not just asking a [question](https://github.com/mtrezza/parse-server-api-mail-adapter#need-help).
- [x ] I have searched through [existing issues](https://github.com/mtrezza/parse-server-api-mail-adapter/issues?q=is%3Aissue).
- [x ] I can reproduce the issue with the [latest version](https://github.com/mtrezza/parse-server-api-mail-adapter/releases). 

### Issue Description
When I try to send a templated email with locale callback the cloud code throws an error 
cannot find function get of undefined

### Steps to reproduce
setup a custom email template with locale callback. 
```
localeCallback: async (user: any) => {
       return user.get('language');
 }
Call it from the cloud code like so:
    Parse.Cloud.sendEmail({
      templateName: "custom_email",
      recipient: a@b.c,
      placeholders: request.params.placeholders
    });
```
(Only works for current Parse server master branch, parse-server 4.5 doesn't have the sendEmail function yet)

### Actual Outcome
Error, cant find method get of undefined error when the locale callback code is executed

### Expected Outcome
Correct locale email gets sent

### Failing Test Case / Pull Request
#18 

###  Environment

- API Mail Adapter version: 1.0.4
- Parse Server version: Master branch

### Logs
don't have them any more^^

**Comment by mtrezza** [comment]
Thanks for reporting. 

This was indeed a missing case that has not been covered. It should be fixed with #18.
