### ISSUE TITLE
Allow placeholders to be used in password reset email and verification email

### ISSUE THREAD

**Issue by mman** [mtrezza/parse-server-api-mail-adapter#36]
### New Feature / Enhancement Checklist

- [ x] I am not disclosing a [vulnerability](https://github.com/mtrezza/parse-server-api-mail-adapter/security/policy).
- [ x] I am not just asking a [question](https://github.com/mtrezza/parse-server-api-mail-adapter#need-help).
- [ x] I have searched through [existing issues](https://github.com/mtrezza/parse-server-api-mail-adapter/issues?q=is%3Aissue).

### Current Limitation
Sending a verification email and requesting a password reset email currently allows only ``username``, ``appName``, and ``link`` variables expansion to be used in a template. Whereas custom emails defined via this adapter allow specification of ``placeholders`` to contain potentially other variables that can be used in the templates. Examples include hero image url, app homepage, etc.

### Feature / Enhancement Description
Please allow ``placeholders`` and/or ``placeholderCallback`` to be specified and used also for ``passwordResetEmail`` and ``verificationEmail`` templates.

### Things to Consider
Looks like this change needs to be coordinated with parse-server UserController.js which hard codes the parameters that are passed into mail adapter.

**Comment by mtrezza** [comment]
Thanks for suggesting.

> Sending a verification email and requesting a password reset email currently allows only username, appName, and link variables expansion to be used in a template. 

This adheres to the current interface definition of Parse Server. It is invoked when Parse Server calls the adapter.

> Whereas custom emails defined via this adapter allow specification of placeholders to contain potentially other variables that can be used in the templates.

You should already be able to do this directly in the adapter's template definition. The adapter should not differentiate between custom templates or email verification / password reset templates.

**Comment by mman** [comment]
@mtrezza So do I understand your reply correctly that it should already be possible? /me confused.

By looking at the code I think it will not work, and placeholders specified in template definition will be ignored, since calls from ``UserController.js`` to mail adapter via methods https://github.com/mtrezza/parse-server-api-mail-adapter/blob/f2455729df5ceb90310d199aad0a79e433725016/src/ApiMailAdapter.js#L75 and https://github.com/mtrezza/parse-server-api-mail-adapter/blob/f2455729df5ceb90310d199aad0a79e433725016/src/ApiMailAdapter.js#L58

ignore the placeholders entirely. Am I missing anything? Will try some time later!

**Comment by mtrezza** [comment]
This is the process:

1. User triggers Parse Server endpoint to send verification email
2. Parse Server invokes `sendVerificationEmail` of email adapter
3. Email adapter looks up template and takes placeholders from adapter configuration
4. Email adapter replaces placeholders in templates

**Comment by mman** [comment]
Let me try it and report back here whether it works as expected.

**Comment by mtrezza** [comment]
I'm closing this because the issue seems to be resolved.
